interface ZIF_BBO_I_ACCOUNTRECEIVABLE_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4E440A',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4EC40A',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4D840A',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4F440A',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4DC40A',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4E840A',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4F040A',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4D640A',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4D240A',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4E240A',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4FA40A',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4F840A',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4FC40A',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4C840A' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZBBO_I_ACCOUNTRECEIVABLE' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4CC40A',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4D440A',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4D040A',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4E040A',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F4CE40A',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ROOT,
 SELECT_ALL                     TYPE /BOBF/OBM_QUERY_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F50240A',
 SELECT_BY_ELEMENTS             TYPE /BOBF/OBM_QUERY_KEY VALUE '0E0D2133B95F1EDA9AA9F0FA7F51040A',
      END OF ROOT,
    END OF SC_QUERY .
endinterface.
